### ISSUE TITLE
Error connecting SSH

### ISSUE THREAD

**Issue by alekhed** [pbogut/vim-dadbod-ssh#1]
Hello!

Can't use ssh connection with dadbod. If i run DBUI i receive error:
sshhost:remotehost:3306 stderr: Welcome to SSH Server 'nostromo'
Error detected while processing function db_ui#open[1]..<SNR>83_init[2]..4[25]..6[5]..13[8]..14[5]..db#resolve[1]..<SNR>85_canonicalize[10]..db#adapter#call[5]..db#adapter#ssh#canonicalize:
line    2:
E117: Unknown function: db#adapter#0#canonicalize

**Comment by pbogut** [comment]
It looks like your connection URI is not correct for this plugin, can you post here full URI you are using?  With credentials obfuscated of course.

**Comment by alekhed** [comment]
[
  {
    "url": "ssh://synchost:mysql://sync:passwd@sync.beget.tech/sync",
    "name": "sync"
  }
]

**Comment by pbogut** [comment]
That makes no sense to me at all. Where is 'ssh://' part? Where is your DB part? What is this table / list?

I am also not sure if this plugin is compatible with DBUI, what I would suggest is make sure that it works with dadbod `:DB` first. Then try to use DBUI.

Go check README.md for usage and how to format URI.

**Comment by alekhed** [comment]
Sorry. Wrong connection string. Updated it. Using :DB i have the same error. 
function get_tunneled_url finishes witout return, so it returns 0, so its incorrect url

**Comment by alekhed** [comment]
For now I see that command begins to work but after second run (after few seconds)

**Comment by pbogut** [comment]
Closing as I have no interest in supporting DBUI. 

If someone is willing to make it work nicer with DBUI I will accept PR for that.

**Comment by pbogut** [comment]
> Sorry. Wrong connection string. Updated it. Using :DB i have the same error.
> function get_tunneled_url finishes witout return, so it returns 0, so its incorrect url

That was really the problem, and there is no reason not to return `new_url` not sure how I missed that in your comments.

**Comment by alekhed** [comment]
sorry/ wrong one
  {
    "url": ***@***.***/sync",
    "name": "sync"
  }


пн, 18 апр. 2022 г. в 17:13, Aleksey Kryukov ***@***.***>:
