### ISSUE TITLE
Database connection on remote SSH server not running on 127.0.0.1

### ISSUE THREAD

**Issue by cknott** [pbogut/vim-dadbod-ssh#11]
I was noticing that if i configure a connection like this ssh://ssh-host:mysql://user:password@db-host-not-localhost/dbname the connection is not possible. I just read the docs and am afraid that this type of connection is not possible.
Is this true and if so, do you know any workarounds?

Thanks in advance!

**Comment by cknott** [comment]
forget it, its an issue with the mysql configuration on the db server.

**Comment by pbogut** [comment]
Yeah, I think it should work. I have similar issue with one server, it only accepts connections from localhost, and when redirecting ports it's not working, mysql is refusing to accept connection.
