### ISSUE TITLE
Unknown Function: wait

### ISSUE THREAD

**Issue by johnnadratowski** [pbogut/vim-dadbod-ssh#2]
I'm getting the following error when attempting to try to run this plugin:

Error detected while processing function db#execute_command[130]..function db#execute_command[30]..db#connect[1]..db#resolve[1]..<SNR>136_canonicalize
[10]..db#adapter#call[5]..db#adapter#ssh#canonicalize[1]..<SNR>138_get_tunneled_url:
line   51:
E117: Unknown function: wait

It seems like it can't find the wait function.  I tried to see if it was the way my VIM was compiled, but no luck.

**Comment by pbogut** [comment]
Looks like `wait()` is NeoVim specific function. This plugin is for NeoVim which is mentioned in the README.md.

I guess it could be updated to support Vim but I have no interest in that so not going to do it myself.
Aside from `wait()` function there will be compatibility issues with jobs  (Vim's API is different).
