### ISSUE TITLE
Free port detection not working on MacOS

### ISSUE THREAD

**Issue by jpagex** [pbogut/vim-dadbod-ssh#5]
Hello!

Thanks a lot for making `vim-dadbod` working with SSH!

As mentioned in the `README`, the open port detection is done for Linux, but not for MacOS.

For people interesting to use it on MacOS, I could make it work by changing the call to `netstat` with `lsof`. See the diff here: https://github.com/pbogut/vim-dadbod-ssh/commit/3e614a6f05c5c017ee2ccd5724386fbd7b2c3819.

```diff
function s:get_free_port()
-  let ports = systemlist("netstat -tuplen 2>/dev/null | grep " . s:localhost
-      \                . " | awk '{print $4}' | sed 's/.*://g'")
+  let ports = systemlist("lsof -nP -iTCP -sTCP:LISTEN | grep " . s:localhost
+      \                . " | awk '{print $9}' | sed 's/.*://g'")
```

Hope this can help someone.

Maybe we could handle both by detecting the OS?

**Comment by zyriab** [comment]
For OS detection, you could do:

```lua
if vim.loop.os_uname().sysname == "Linux" then
    -- your script
end
```

On MacOS 13.3.1 (Ventura), `vim.loop.os_uname().sysname` returns `Darwin`

Cheers

**Comment by pbogut** [comment]
You can make a pull request with that change and OS detection, I'm happy to merge it.

**Comment by ZyriabDsgn** [comment]
Will do after work today :)
