### ISSUE TITLE
2 connection to different SSH hosts.

### ISSUE THREAD

**Issue by BioWare** [pbogut/vim-dadbod-ssh#9]
Just a question.
I'm not really good at this, but according to information on the internet, it's possible to have 2 SSH connections to different hosts.

Right now, I have 2 databases: one on the dev host and the other on the prod host. 

I can connect to them separately on the first neovim run.
However, if I open a dev connection on the first Neovim run, then I can't open a connection to the prod databases. Is there a way to fix this? 

Can you give me a link to study this theme? I would be grateful. 

Thanks for your plugin; it really helped me.

**Comment by pbogut** [comment]
I use many different ssh connections at the same time, and all works fine. From your description it's hard to tell what's not working for you. Can you give me an example?

I'll give you my example:
```vimrc
let g:con1 = 'ssh://server1ip:mysql://login:password@127.0.0.1/somename'
let g:con2 = 'ssh://server2ip:mysql://login:password@127.0.0.1/othername'
```

Now if you run:
`:DB g:con1 show tables`
and 
`:DB g:con2 show tables`

Both command should show tables from different databases. You can use `:DB g:conn1 \dt` if you are using postgres, or simple `:DB g:conn1` to start interactive mode. All works for me with no issues.

**Comment by BioWare** [comment]
Yeah, sorry for not giving an example and not mentioning that I'm using dadbod-ui.

//dad-bod-ui.lua
```lua
vim.g.dbs = {
    --dev connections
    {
        name = 'dev_back',
        url = 'ssh://dev_ssh_host:mysql://username:password@host_ip/db_name',
    },
    --dev connections

    --prod connections
    {
        name = 'prod_back',
        url = 'ssh://prod_ssh_host:mysql://username:password@host_ip/db_name',
    },
    --cinemaxDB
    {
        name = 'cinemax_prod',
        url = 'ssh://prod_ssh_host:mysql://username:password@host_ip/db_name',
    },
}
```
There is 2 different hosts. 1 dev, 2 prod.
so when i first time open my neovim. I'm using DBUI (dad-bod-ui).
Choosing connection that i need
![Screenshot from 2024-03-07 12-16-18](https://github.com/pbogut/vim-dadbod-ssh/assets/38793673/700b8753-3922-4581-a64c-4612a3d7936d)
it's connection and working. 
Than if i will choose db in list from prod host it will give me an error 
![Screenshot from 2024-03-07 12-18-08](https://github.com/pbogut/vim-dadbod-ssh/assets/38793673/5dab5e35-2894-4a02-88e2-4b77f19aaada)
access denied for user.

It turns out that he is trying to connect using the first ssh connection

**Comment by pbogut** [comment]
It works for me, I've set up many different connections, they all work fine all together.

I tried this:
2 connections through same ssh server to same db server (different databases though).
2 connections through same ssh server to 2 different db servers.
2 connections through 2 different ssh servers to 2 different db servers.

They all work fine, I've set up combination of 8 connections and I can connect to all of them at the same time with no issues.

Do you have problem with any specific combination, or it's just that only one connection is working and no matter which one you try to connect next does not work?

Maybe your production server allows you for only one ssh connection? Can you open two terminals and ssh from both to your server at the same time?

Another reason may be that free port detection is not working correctly, and after first connection, when prot 7000 is taken another connection can not be made at the same port. Do you use Mac or Linux? Can you run this command for me:

Linux:
```
netstat -tuplen 2>/dev/null | grep 127.0.0.1 | awk '{print $4}' | sed 's/.*://g'
```

Mac:
```
lsof -nP -iTCP -sTCP:LISTEN 2>/dev/null | grep 127.0.0.1 | awk '{print $9}' | sed 's/.*://g'
```

It should display list of ports that are used on your machine. Can you confirm this command works correctly on your machine?

**Comment by BioWare** [comment]
hey thanks for yourn help and time.
i have this problem
> 2 connections through 2 different ssh servers to 2 different db servers.

`netstat -tuplen 2>/dev/null | grep 127.0.0.1 | awk '{print $4}' | sed 's/.*://g'`
this command shows nothing.

2 can connect to 2 ssh from terminal. So it's not a block from server side.
It's ok. I will fix it later. Thanks for giving me information. Now i know where to watch.

**Comment by pbogut** [comment]
If this command shows nothing, then that's most likely the problem. It should return list of ports that are in use, so that the plugin can pick free port for ssh tunnel (one port is required per connection). Since command returns nothing, same port is used for second connection, and since it's already taken tunnel is not working and DB connection can not be established. I'll have to check the code to be 100% sure that this is the problem. Will let you know.

**Comment by pbogut** [comment]
You can try to update plugin and see if it works now. I've changed how ports are checked, so now for every new connection new port should be used. 

Just keep in mind it's really a workaround, the core issue here is that free port detecting is not working, if you try to open nvim twice and access SSH DB in both it will still be broken. But for one instance you should be able to open many connections. 

Please, let me know if that helped.

**Comment by BioWare** [comment]
Hey @pbogut thanks a lot for your help. It did help me.

Can you please give me some sources to study, to improve my knowledge? 

Thanks for your job.
